//all types of actions here

//Profile actions
export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST"
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS"
export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE"

//Auth actions
export const FETCH_AUTH_REQUEST = "FETCH_AUTH_REQUEST"
export const FETCH_AUTH_SUCCESS = "FETCH_AUTH_SUCCESS"
export const FETCH_AUTH_FAILURE = "FETCH_AUTH_FAILURE"
export const DELETE_AUTH_TOKEN = "DELETE_AUTH_TOKEN"

//Plan actions
export const FETCH_UPDATE_PLAN_REQUEST = "FETCH_UPDATE_PLAN_REQUEST"
export const FETCH_UPDATE_PLAN_SUCCESS = "FETCH_UPDATE_PLAN_SUCCESS"
export const FETCH_UPDATE_PLAN_FAILURE = "FETCH_UPDATE_PLAN_FAILURE"

//updateTask actions


//Actions for new employees
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES"
export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS"
export const FETCH_EMPLOYEES_FAILURE= "FETCH_EMPLOYEES_FAILURE"
export const FETCH_DIRECTORS_SUCCESS = "FETCH_DIRECTORS_SUCCESS"
export const FETCH_DIRECTORS_FAILURE= "FETCH_DIRECTORS_FAILURE"


//Clean all
export const CLEAN_ALL = "CLEAN_ALL"

//Notifications actions